### ISSUE TITLE
Html теги поддерживаемы внутри параграфа

### ISSUE THREAD

**Issue by audetv** [audetv/book-parser#3]
Внутри параграфа бывает текст:
1. выделенный жирным
2. курсив

Сейчас парсер при обработке обрамляет текст в теги b, i 
Нужно ли это?

П.С. Сноски сделал в скобках и обрамил каждую строку сноски с жестким переносом в тег span (его потом можно стилизовать в выдаче, и он семантически является продолжением строки, а не новый блок типа параграф)

Пример с i, месиво тегов из word, но при отображении все будет ок, так что можно не обращать внимания, так хранит word/docx в xml, и когда теги из xml заменяем на html, получаем такой результат, структура соблюдена, просто иногда 1 буква выделена, а потом остальная часть слова, машине это не важно, можем не заниматься исправлением этого:

`219ef85b-29e5-41ed-a1dc-a34db5134844	93e11768-dd86-4c4b-a740-228f11216e24	<p><i>Вследствие этой особенности ритуала исторически реального и</i><i>с</i><i>лама смысл Корана остается недоступным для многих неарабоязычных мусульман, а тем более — для остального населения. И эта недосту</i><i>п</i><i>ность смысла Корана вполне устраивает вождей патриотизма, из чи</i><i>с</i><i>ла верноподданных православной иерархии.</i></p>`

Пример с b;
`54ad205e-d5ee-4b28-b690-a54a9d17321b	93e11768-dd86-4c4b-a740-228f11216e24	<p>Приведенный <b>мировоззренческий стандарт для внутреннего прав</b><b>о</b><b>славного употребления </b>взят из публикации в еженедельнике “Итоги” от 24 ноября 1998 г., где освещается попытка ликвидации в судебном порядке московской организации “Свидетелей Иеговы” по иску прокуратуры Северного округа столицы. Среди всего прочего была предпринята попытка обвинить иеговистов в разжигании религиозной розни.</p>`

Пример параграфа с обработанной сноской, тут в круглых скобках текст из сноски `( <span>Инквизиция это орган,...</span>)`:

`5712107b-92f6-4d6c-845d-c04add09cfb9	93e11768-dd86-4c4b-a740-228f11216e24	<p>Но, если обстановка сложится иначе, то можно в <i>проскрипционный</i> список 2000 религиозных деструктивных течений внести и Ислам; да и вообще ко всему не совпадающему с канонами и традициями исторически сложившегося православия подходить по-инквизиторски <i>(вопреки тому, </i><i>что Христос не учреждал инквизиции</i><i>(<span> Инквизиция это орган, посредством которого “хороший” демонизм борется со всем, что отождествляет с “плохим” демонизмом.</span>)</i><i>), </i>что в отношении “Свидетелей Иеговы” попробовала осуществить на основе двойных нравственно-этических стандартов якобы светская прокуратура Северного округа столицы.</p>`

**Comment by iprst** [comment]
> Нужно ли это?

Неизвестно. Мне в целом не нужно, от форматирования книг ВП СССР всегда в глазах рябит. 

> Сноски сделал в скобках и обрамил каждую строку сноски с жестким переносом в тег span (его потом можно стилизовать в выдаче, и он семантически является продолжением строки, а не новый блок типа параграф)

Эта идея кажется отличной. 

> Пример с i, месиво тегов из word, но при отображении все будет ок, так что можно не обращать внимания, так хранит word/docx в xml, и когда теги из xml заменяем на html, получаем такой результат, структура соблюдена, просто иногда 1 буква выделена, а потом остальная часть слова, машине это не важно, можем не заниматься исправлением этого:

Нужно ли вообще хранить это форматирование, вот вопрос. [Здесь](https://github.com/iprst/Geomatrix/issues/37#issuecomment-1575496479) вы правильно задали вопрос о docx и txt форматах. У меня этот вопрос тоже неоднократно всплывал. Если кратко — сейчас docx нужен только для того, чтобы разметить названия глав. Что вообще не критично и на самом деле можно этого не делать. Всё остальное в ворде только мешает: страницы, заголовки, пагинация, оформление, сноски, примечания — всё это просто мусор с точки зрения работы с информацией. В принципе можно прямо в VBA написать скрипт для очистки всего и вся, но я не смог, нашёл только вариант с удалением заголовков страниц, нумерации и футеров, он работает отлично. перевод сносок в примечания и последующий перевод их в текст выполняется надстройкой Kutools. После этого, по сути, у нас на руках текст, который от txt отличается лишь наличием оформления заголовков, всё остальное в принципе суммируется в переносы строки — мягкие или жёсткие, которые по видимому в текстовых редакторах можно зафиксировать через регулярные выражения.

**Comment by iprst** [comment]
> Сейчас парсер при обработке обрамляет текст в теги b, i

Думаю жирный и курсив из оригинальной разметки нам не потребуются. 

Для словарей и энциклопедий отработан [способ приведения текста в наиболее элементарное состояние](https://github.com/iprst/Geomatrix/issues/37#issuecomment-1575587810) как «набора строк» с переносами строки между ними и с возможностью минимальной разметки внутри параграфа-строки, которая будет в режиме строки представлять  конструкцию из символов пробел-слэш-слэш-пробел ` // `, и которую можно будет либо использовать для организации тегов, либо оставить в строке, либо просто удалить.

**Comment by audetv** [comment]
#4 Удалил жирный и курсив из разметки (это самое простое, закомментировать пару строк кода)
